name: Solar system workflow

on:
  workflow_dispatch:
  push:
     branches:
       - main
       - 'feature*'

jobs:
   unit-testing:
        name: Unit testing
        #strategy:
         #   matrix:
          #      nodejs_version: [18, 19, 20]
           #     - nodejs_version: 18
            #        operating_system: macos-latest
        #runs-on: ${{matrix.operating_system}}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup nodejs version-18
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: cache npm dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ubuntu-latest-node-modules-${{ hashfiles('package-lock.json') }}

        - name: Install dependencies
          run: npm install

        - name: Unit testing
          continue-on-error: true
          id: nodejs-unit-testing-step
          run: npm test
        
        - name: status of testing
          #if: always()    ## we can add if: always() means if previous stpe will pass or fail then this step will run always
          run: echo "Tetsing is failed"   ##testing cache

   docker-login:
    needs: unit-testing
    runs-on: ubuntu-latest
    permissions:
            packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     # - name: Login to github container registry 
     #   uses: docker/login-action@v3
     #   with:
     #    registry: ghcr.io
     #     username: ${{ github.repository_owner }}
     #     password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker build for testing
        uses: docker/build-push-action@v4
        with:
           context: .   ## Accept the path where you have docker file in our case dockerfile present in root directory in repo
           push: false
           tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}  ## version will be dynamically changes with sha value of commit id.

      - name: docker image testing
        run: |
            docker images
            docker run -it -d --name solar-system \
               -p 3000:3000 \
               ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker/Github registry push
        uses: docker/build-push-action@v4
        with:
           context: .   ## Accepts the path where you have docker file in our case dockerfile present in root directory in repo
           push: true
           tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}  ####ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
           
   dev-deploy:
    if: contains(github.ref, 'feature')   ## this job wil only run if the current branch will be feature
    needs: docker-login
    uses: ./.github/workflows/reuse-deployment.yaml
    secrets:
      k8s-kubeconfig: ${{ secrets.KUBECONFIG }}   ## This is how we can pass secret from caller workflow to called workflow
    #with:                                              
       # mongodb-uri: #{{ vard.MONGO_URI }}   we are calling variable using with which we have defined in reusalble workflow
    with:
      environment: development
      k8s-manifest-dir: kubernetes/development/


   integration-testing:
    if: contains(github.ref, 'feature') 
    name: Dev Integration tetsing
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - name: test url output using curl and jq
        #env:
          #URL: {{ needs.dev-deploy.outputs.APP_INGRESS_URL }}   # we are using the output from one job to other
        run: |
            echo "hello dev is working fine for solar system"



   prod-deploy:
    if: github.ref == 'refs/heads/main'   ## only deployed in main branch
    needs: docker-login
    uses: ./.github/workflows/reuse-deployment.yaml     ## this is the caller workflow here we uses the relative path of reusable workflow file
    secrets:
      k8s-kubeconfig: ${{ secrets.KUBECONFIG }} 
    #with:
       # mongodb-uri: #{{ vard.MONGO_URI }}   
    with:
      environment: production      
      k8s-manifest-dir: kubernetes/development/                                          ## NOTE: Secrets will not be called from reusable workfloe file for that we need to use 
                                                            ##  secrets = inherit  or 
   prod-integration-testing:
    if: github.ref == 'refs/heads/main' 
    name: Prod Integration tetsing
    needs: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: test url output using curl and jq
        #env:
          #URL: {{ needs.dev-deploy.outputs.APP_INGRESS_URL }}   # we are using the output from one job to other
        run: |
            echo "hello dev is working fine for solar system"
        





           

       
