name: Solar system workflow

on:
  workflow_dispatch:
  push:
     branches:
       - main
       - 'feature*'

jobs:
   unit-testing:
        name: Unit testing
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                operating_system: [ubuntu-latest, macos-latest]
                exclude:
                  - nodejs_version: 18
                    operating_system: macos-latest
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup nodejs version-${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Install dependencies
          run: npm install

        - name: Unit testing
          run: npm test

        - name: Archieve test result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha test result
            path: test-results.xml

    code-coverage:
      name: Code Coverage
      runs-on: ububtu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@

        - name: Setup nodejs dependencies
          uses: actions/setup-node@v3

        - name: Install dependencies
          run: npm install

        - name: check code coverage
          run: npm run coverage

        - name: Archieve test result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
        
