name: Solar system workflow

on:
  workflow_dispatch:
  push:
     branches:
       - main
       - 'feature*'

jobs:
   unit-testing:
        name: Unit testing
        #strategy:
         #   matrix:
          #      nodejs_version: [18, 19, 20]
           #     - nodejs_version: 18
            #        operating_system: macos-latest
        #runs-on: ${{matrix.operating_system}}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup nodejs version-${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Install dependencies
          run: npm install

        - name: Unit testing
          continue-on-error: true
          run: npm test
        
        - name: status of testing
          run: echo "Tetsing is failed"